module.exports = {
    argentina: 'ar',
    australia: 'au',
    brazil: 'br',
    canada: 'ca',
    china: 'cn',
    germany: 'de',
    greece: 'gr',
    india: 'in',
    israel: 'is',
    norway: 'no',
    southkorea: 'kr',
    switzerland: 'ch',
    thailand: 'th',
    unitedkingdom: 'gb',
    unitedstatesofamerica: 'us',
};
