module.exports = {
    argentina: 'ar',
    australia: 'au',
    austria: 'at',
    brazil: 'br',
    canada: 'ca',
    china: 'cn',
    france: 'fr',
    germany: 'de',
    greece: 'gr',
    india: 'in',
    ireland: 'ie',
    israel: 'il',
    italy: 'it',
    newzealand: 'nz',
    norway: 'no',
    portugal: 'pt',
    southkorea: 'kr',
    switzerland: 'ch',
    thailand: 'th',
    unitedarabemirates: 'ae',
    unitedkingdom: 'gb',
    unitedstatesofamerica: 'us',
};
